import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Comforter } from "next/font/google";

const inter = Comforter(
    {
        subsets: ['latin'],
        weight: '400',
    }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={ inter.className }>
          {children}
      </body>
      </html>
  );
}
